import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import SmoothScroll from "./SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          {children}
        </SmoothScroll>
        <Script src="https://static.elfsight.com/platform/platform.js" async />
      </body>
    </html>
  );
}
